<a href="https://colab.research.google.com/github/poprostuVEX/Kurs-AI/blob/main/lekcja78.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#print(array)
#print(np.shape(array))
array2x6 = array.reshape(2,6)
print(array2x6)
print(np.shape(array2x6))


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [9]:
import numpy as np
unsorted = np.array([5,1,4,6,7,8,22,2,-9,0])
print(unsorted)
sorted=np.sort(unsorted)
print(sorted)

[ 5  1  4  6  7  8 22  2 -9  0]
[-9  0  1  2  4  5  6  7  8 22]


In [11]:
unsorted2D= np.array([5,1,4,6,7,8,22,2,-9,0[2,3,5,3,-55,444,3]])
sorted2D_axis1 = np.sort(unsorted2D,axis=1)
print(f"Tablica posortowana wzdłuż krawędzi 1:\n{sorted2D_axis1}")

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
/tmp/ipython-input-116640249.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  unsorted2D= np.array([5,1,4,6,7,8,22,2,-9,0[2,3,5,3,-55,444,3]])


TypeError: 'int' object is not subscriptable

In [143]:
from numpy import random
for i in range (10):
  print(random.rand()*2 - 1)

-0.3598368873481599
0.20012931200142936
0.5895351104554836
-0.918988113091924
0.32143145155284425
-0.2581400069375668
-0.44200108469158983
-0.5632037987479626
-0.30314408199598697
0.3949815479663843


In [137]:
dates = [1241, 972, 1605, 1444, 1683]

In [144]:
array1D = np.array([1,2,3,4,5,6,7,8,9])
print(array1D[2:5])

[3 4 5]


In [147]:
array2D = np.array([[7, 2, 9],
              [4, 8, 1],
              [5, 6, 3]])

for i in np.nditer(array2D):
  print(i)


7
2
9
4
8
1
5
6
3


In [151]:
binary_mask= np.where(array2D %2==0)
print(binary_mask)
print(array2D)


(array([0, 1, 1, 2]), array([1, 0, 1, 1]))
[[7 2 9]
 [4 8 1]
 [5 6 3]]
